### PR TITLE
update to cart 0.2.0

### PR DESCRIPTION
**Pull request by dpatil-magento**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs:
- https://update-cart--boilerplate-commerce-dropins--hlxsites.hlx.live/

### CODE REVIEW

**Comment by dpatil-magento** [comment]
@fnhipster  Cart dropin needs tools 0.24.0 but rest dropins were on old tools version. I dont see any UI issues, but wanted to cross check if its ok to use tools 0.24.0?

**Review by fnhipster — APPROVED** [review]

**Comment by fnhipster** [comment]
> @fnhipster Cart dropin needs tools 0.24.0 but rest dropins were on old tools version. I dont see any UI issues, but wanted to cross check if its ok to use tools 0.24.0?

That's ok. It should be backward compatible.

**Comment by sirugh** [comment]
Did you see this error in console?

image

**Comment by dpatil-magento** [comment]
created new pr https://github.com/hlxsites/boilerplate-commerce-dropins/pull/60

**Pull request closed without merging**
